# Generated by Django 5.1.1 on 2024-09-17 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

 initial = True
dependencies = [
  migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

operations = [
 migrations.CreateModel(
  name='Post',
  fields=[
 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
 ('title', models.CharField(max_length=100)),
 ('content', models.TextField()),
 ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
 ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
	('first_name', models.CharField(max_length=30)),
 ('surnname', models.CharField(max_length=30)),
 ('Email', models.CharField(max_length=100)),
 ('ADDRESS_1', models.CharField(max_length=30)),
 ('ADDRESS_2', models.CharField(max_length=30)),
 ('ADDRESS_3', models.CharField(max_length=30)),
 ('ADDRESS_4', models.CharField(max_length=30)),
 ('ADDRESS_5', models.CharField(max_length=30)),
 ('CODE',models.CharField(max_length=100))
 ('WHY', models.TextField(max_length=1000))
 ('MAILING_LIST', models.ForeignKey(User, on_delete=models.CASCADE))
            ],
        ),
        ]
